---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cilium-etcd-secrets
  namespace: kube-system
data:
  # To enable TLS with etcd, populate the secret with the key information from
  # etcd:
  #
  # kubectl create secret generic -n kube-system cilium-etcd-secrets \
  #    --from-file=etcd-ca=ca.crt \
  #    --from-file=etcd-client-key=client.key \
  #    --from-file=etcd-client-crt=client.crt
